blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/xnephilim
    about: Join our Discord
  - name: ShapeShift Forum
    url: https://forum.xnephilim.com/
    about: Check out the forum
